[2025-08-24T19:32:15.083+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl.load_weather manual__2025-08-24T19:32:12.291093+00:00 [queued]>
[2025-08-24T19:32:15.091+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl.load_weather manual__2025-08-24T19:32:12.291093+00:00 [queued]>
[2025-08-24T19:32:15.092+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-24T19:32:15.103+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_weather> on 2025-08-24 19:32:12.291093+00:00
[2025-08-24T19:32:15.108+0000] {standard_task_runner.py:60} INFO - Started process 185 to run task
[2025-08-24T19:32:15.110+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_etl', 'load_weather', 'manual__2025-08-24T19:32:12.291093+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmpayukfbgv']
[2025-08-24T19:32:15.112+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask load_weather
[2025-08-24T19:32:15.178+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_etl.load_weather manual__2025-08-24T19:32:12.291093+00:00 [running]> on host 7b1c3b0dd09a
[2025-08-24T19:32:15.349+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl' AIRFLOW_CTX_TASK_ID='load_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-08-24T19:32:12.291093+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-24T19:32:12.291093+00:00'
[2025-08-24T19:32:15.369+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-08-24T19:32:15.374+0000] {sql.py:450} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS weather_data (
        id SERIAL PRIMARY KEY,
        city VARCHAR(50),
        date DATE,
        temperature FLOAT,
        humidity INT,
        condition VARCHAR(50)
    );
    , parameters: None
[2025-08-24T19:32:15.388+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-08-24T19:32:15.392+0000] {sql.py:450} INFO - Running statement: 
    INSERT INTO weather_data (city, date, temperature, humidity, condition)
    VALUES (%s, %s, %s, %s, %s)
    , parameters: ('New York', '2025-08-24', 25.92, 65, 'Clouds')
[2025-08-24T19:32:15.393+0000] {sql.py:459} INFO - Rows affected: 1
[2025-08-24T19:32:15.395+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-24T19:32:15.402+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_etl, task_id=load_weather, execution_date=20250824T193212, start_date=20250824T193215, end_date=20250824T193215
[2025-08-24T19:32:15.445+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-24T19:32:15.458+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
